function DxaDxbDvaDvb = fixedcexp2b(t, getxv, Fa, Fb, Fm, r, ma, mb, N)
    Dxa = zeros(N, 1);
    Dxb = zeros(N, 1);
    Dva = zeros(N, 1);
    Dvb = zeros(N, 1);
    imolecule = 1:N;
    iforce = 2:N;
    xa = getxv(imolecule);
    xb = getxv(N + imolecule);
    va = getxv(2*N + imolecule);
    vb = getxv(3*N + imolecule);
    Dxa(imolecule) = va(imolecule);
    Dxb(imolecule) = vb(imolecule);
    ravalue(iforce) = xa(iforce) - xa(iforce-1);
    rbvalue(iforce) = xb(iforce) - xb(iforce-1);
    rmvalue(imolecule) = xb(imolecule) - xa(imolecule);
    Favalue(iforce) = subs(Fa, r, ravalue(iforce));
    Fbvalue(iforce) = subs(Fb, r, rbvalue(iforce));
    Fmvalue(imolecule) = subs(Fm, r, rmvalue(imolecule));
    imolecule = 2:(N-1);
%   Dva(1) = 0;
    Dva(imolecule) = (-Favalue(imolecule+1)+Favalue(imolecule)-Fmvalue(imolecule))/ma;
    Dva(N) = (Favalue(N) - Fmvalue(N))/ma;
    Dvb(1) = (-Fbvalue(2) + Fmvalue(1))/mb;
    Dvb(imolecule) = (-Fbvalue(imolecule+1)+Fbvalue(imolecule)+Fmvalue(imolecule))/mb;
    Dvb(N) = 0;
    DxaDxbDvaDvb = [Dxa; Dxb; Dva; Dvb];
    